LOCAL_PATH := $(call my-dir)

#include $(CLEAR_VARS)
#
#LOCAL_MODULE := hsbase
#LOCAL_SRC_FILES := @LIBHSBASENAME@
#
#include $(PREBUILT_SHARED_LIBRARY)
#
#include $(CLEAR_VARS)
#
#LOCAL_MODULE := hsint
#LOCAL_SRC_FILES := @LIBHSINTEGERNAME@
#
#include $(PREBUILT_SHARED_LIBRARY)
#
#include $(CLEAR_VARS)
#
#LOCAL_MODULE := hsprim
#LOCAL_SRC_FILES := @LIBHSPRIMNAME@
#
#include $(PREBUILT_SHARED_LIBRARY)
#
#include $(CLEAR_VARS)
#
#LOCAL_MODULE := hsrts
#LOCAL_SRC_FILES := @LIBHSRTSNAME@
#
#include $(PREBUILT_SHARED_LIBRARY)
#
#include $(CLEAR_VARS)
#
#LOCAL_MODULE := hsffi
#LOCAL_SRC_FILES := @LIBHSFFINAME@
#
#include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)

LOCAL_MODULE := app
LOCAL_SRC_FILES := stub.c

include $(BUILD_SHARED_LIBRARY)
